### ISSUE TITLE
All of the rightclick options use wrong file / do nothing

### ISSUE THREAD

**Issue by wlfbck** [Everspace/vsc-rightclick-git#2]
Title basically says it all. There are three cases which can happen:

1. Does nothing.
2. Adds a completely unrelated file.
3. Adds the currently displayed file.

No idea what happens exactly. It works semi reliably when i open the file i want to rightclick first and then use the rightclick menu. Which is simply not possible for folders for example.

**Comment by Everspace** [comment]
This is now fixed in 2.0
