### ISSUE TITLE
does this only show the menu options in the Explorer?

### ISSUE THREAD

**Issue by gregveres** [Everspace/vsc-rightclick-git#3]
I think I mistakenly expected this to put the options in the context menu in the editor. That is where I expected and wanted the menu choice.

But then you responded to my review in a way that made me look at the image in the extension's description and I see that it shows the explorer pane open. 

If it is meant to only show the SCM options on the explorer, then it is working as expected and I will remove my review that says it doesn't work. I think the more convenient place to have these options is the context menu in the editor itself though.

**Comment by Everspace** [comment]
It is only supposed to show the SCM options on the explorer.
