### ISSUE TITLE
Add option to add file from file tab or custom button

### ISSUE THREAD

**Issue by artrz** [Everspace/vsc-rightclick-git#9]
Hey @Everspace. Thanks for such a nice extension. I commonly find myself needing to add a file directly from the editor and switching to the file tree and finding the file is kinda tedious. This could by solved by adding a menu item on file tab contextual menu or as a button at the top right of the editor. I can send a PR for it if you're interested.

**Comment by Everspace** [comment]
If you could do that @artrz that would be great.
